train = true
training_runs = 0   # 0 = single run with fixed seed for reproducibility

[experiment]
type = "country"    # "country" | "regions"

[data]
window_size    = 336    # 24*7*2 (2 weeks)
horizon_type   = "hour"
horizon_length = 168
label_len      = 0
batch_size     = 128

[training]
patience       = 50
learning_rate  = 0.01
train_epochs   = 1

[model]
type = "baseline"    # "autoformer" | "linear" | "baseline" | "sarimax"
