train = true
training_runs = 0   # 0 = single run with fixed seed for reproducibility

[experiment]
type = "country"

[data]
window_size    = 336    # 24*7*2 (2 weeks)
horizon_type   = "hour"
horizon_length = 168    # 24*7 (1 week)
label_len      = 0
batch_size     = 128

[training]
patience       = 50
learning_rate  = 0.00003
train_epochs   = 3000

[model]
type            = "linear_baseline"
include_holiday = true
exog_cols       = ["temp_media"]
